/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.13.0+p3-g40b6564e
 *
 * Project: 'lab_05+lab_05' 
 * Target:  'lab_05' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H



#endif /* RTE_COMPONENTS_H */
